version: "3.1"
services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: ./
    container_name: frontend
  api:
    build:
      dockerfile: api.Dockerfile
      context: ./
    container_name: api
    depends_on:
      - mongo
      - frontend
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:example@mongo:27017/
      JWT_SECRET: banana
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
