apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: lbk2kdocker/api:5
          imagePullPolicy: Always
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: mongo-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: mongo-password
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: mongo-host
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt-secret
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
