apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: lbk2kdocker/api:6
          env:
            - name: PORT
              value: "3000"
            # - name: MONGO_USERNAME
            #   value: username
            # valueFrom:
            #   secretKeyRef:
            #     name: my-secret
            #     key: mongo-username
            # - name: MONGO_PASSWORD
            #   value: password
            # valueFrom:
            #   secretKeyRef:
            #     name: my-secret
            #     key: mongo-password
            # - name: MONGO_HOST
            #   value: mongo-service
            # valueFrom:
            #   secretKeyRef:
            #     name: my-secret
            #     key: mongo-host
            - name: JWT_SECRET
              value: test
            # valueFrom:
            #   secretKeyRef:
            #     name: my-secret
            #     key: jwt-secret
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
