# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mongo-express-deployment
#   labels:
#     app: mongo-express
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongo-express
#   template:
#     metadata:
#       name: mongo-express
#       labels:
#         app: mongo-express
#     spec:
#       containers:
#         - name: mongo-express
#           image: mongo-express
#           env:
#             # - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
#             #   value: "true"
#             # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#             #   value: username
#             # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#             #   value: password
#             # - name: ME_CONFIG_MONGODB_SERVER
#             #   value: mongo-service
#             - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#               value: username
#             - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#               value: password
#             - name: ME_CONFIG_MONGODB_URL
#               value: mongodb://username:password@mongo-service:27017/
#             # valueFrom:
#             #   configMapKeyRef:
#             #     name: mongo-secret
#             #     key: mongo-url
#           resources:
#             requests:
#               cpu: 100m
#               memory: 100Mi
#             limits:
#               cpu: 100m
#               memory: 100Mi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-express-service
# spec:
#   # it is default cluster ip
#   type: LoadBalancer
#   selector:
#     app: mongo-express
#   ports:
#     - port: 8081
#       targetPort: 8081
