apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            # valueFrom:
            #   secretKeyRef:
            #     name: mongo-secret
            #     key: username
            # valueFrom:
            #   secretKeyRef:
            #     name: mongo-secret
            #     key: password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # it is default cluster ip
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
