apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce"
    # - "ReadOnlyMany"
    # - "ReadWriteMany"
  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  volumeName: mongo-pv
  storageClassName: standard
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 3Gi
