apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 1000Mi
          ports:
            - containerPort: 27017
          # env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: username
          # valueFrom:
          #   secretKeyRef:
          #     name: my-secret
          #     key: mongo-username
          # - name: MONGO_INTDB_ROOT_PASSWORD
          #   value: password
          # valueFrom:
          #   secretKeyRef:
          #     name: my-secret
          #     key: mongo-password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  # ClusterIP: none
  # clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
